dist: focal
language: php

php:
  - 8.2
  - 8.3

env:
  global:
    - secure: "NqL3njJKK47o4+21a4E8at3zA8TL/lQBygBIepzUdUNloMM5asII+y+IvF+HZuX7PAkpuEK11tYIeAUF0G16d7k1wxgVC2MRwZA4vjaOmqYD8Ag6HzDlebynT+sqasvoL3r9BGpJsTpAVW8b2XBzMkodYTDOhtGiNuPAja9J1OEfgGHffRkrF1u8fsn4z6ZAFvu+/O1nRj4jNla34ifKbciD/aEnlHdyIPUHkAGqYfwyooNPUkiggJ7W4y1Vaq66+vH8bibiC8MeyFqRVArav79Q+nIIhY/AVEJqysq+aoXVGFtN1xcDN7cFP9rend0NuhokPrIf/6OaXj4n7B4Pgx/4BAvQVFRuPzKVF54uTuDQ0MciukxnPGK8pLj9UnuNdOcsDrqcAwGK+kW5wv84NCj62qhtU54kZ24cEuT+8Gz7XGMWCE20Tq0DaS6QRoHutWV6rEcn/HD+WcMY9H+H/5xEs+dYkZptSXGJ6BPp8gkld9WkkqK+dojbyhzD3NLKTwMz09mIcDxyLwwPrz3F/N1fpLT63gIIe58c1AaHIugEmIH2XWZ7LK5vQhAZQsj87AR3Vt6SYCEMKvK0FnB/1P3Eh5J23lh0h+Av0X0g7W/C/Azh1HaB3OBuOZpbZnJ87s2s46B/oIsjnjkum1p+FqHWV4ENbMXoXAJewCSiPp8="
    - DB_CONNECTION=mysql
    - DB_DATABASE=testing
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - MAIL_MAILER=log
    - XDEBUG_MODE=coverage

cache:
  directories:
    - node_modules
    - vendor

before_install:
  - sudo apt-get update -y
  - sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean -y
  - sudo rm -rf /etc/mysql
  - sudo apt-get install apt-transport-https curl -y
  - sudo mkdir -p /etc/apt/keyrings
  - sudo apt install -y software-properties-common
  - sudo sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
  - sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] https://mariadb.mirror.liquidtelecom.com/repo/11.4/ubuntu focal main'
  - sudo apt update -y
  - sudo apt-get -y install mariadb-server mariadb-client
  - sudo apt-get install php-xdebug

before_script:
  - cp .env.travis .env
  - sudo mariadb -e 'CREATE DATABASE testing;'
  - sudo mariadb -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY '';"
  - sudo mariadb -e "GRANT ALL ON testing.* TO 'travis'@'localhost';"
  - echo "auto_globals_jit = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install --no-interaction
  - composer require --dev php-coveralls/php-coveralls
  - php artisan key:generate
  - sed -i "s/^LITTLEJWT_KEY_PHRASE=.*/LITTLEJWT_KEY_PHRASE=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - sed -i "s/^LITTLEJWT_KEY_PHRASE_REFRESH=.*/LITTLEJWT_KEY_PHRASE_REFRESH=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - php artisan migrate --no-interaction -vvv
  
script:
  - mkdir -p build/logs
  - php artisan test --coverage-clover build/logs/clover.xml

after_success:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN php vendor/bin/coveralls.php -v
