dist: focal
language: php

php:
  - 8.2
  - 8.3

env:
  global:
    # Don't set the COVERALLS_REPO_TOKEN env variable. Coveralls will use the Travis CI env variable to reference the repo token.
    - DB_CONNECTION=mysql
    - DB_DATABASE=testing
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - MAIL_MAILER=log
    - XDEBUG_MODE=coverage
    - secure: "FVYTS6pmgE//NzwAstQggWLMgDFzaDuuXYD4GFH8kg2fDEqvZjSDaXY/HHdDqd8as0x7dxRYP3pStmf1Hryigo8ML4Bp7st483xc4y6YKfCG7WXlEu3N8xu2ynJRC5OQWzX858wEfnf/vHaqkKhFZsDUhvTFmCnpSoTpDtA5qwHgUB5m8Y+e8j4ZePcDiaU2Nnlo3gW4xzecH1hynuy7xIiNzWqjUFDs3dinj0q8EOCFS1Mvgd2UxGaxwQ4amXWyKEJy/3jm7Pi/e7b/G8Tpmv77PQiybGC1ehARtzuwcgqDugzGsOag5SO2OuJXwW+zOmxxBOSXgX+YoJZhyzup5GcfxZpXLjRjTN3tBoQw4qnkTEBh+vdinHR7FtjZTuKfcJybpv1WQYFDJ44xdaXs00jYg3HqgI7aa8iooeiW+YXkMp3ww4kZPa6IHmGDh/OgbOQDAP5Z0FDKQDmE6/YeGNO04LzZCbJc9ln8tpe22ZYdQVEZsrajup4ftHBDkOt87BlrBMdw/Mpu/QGWZPzK890ZJm6UbdOtFt/q9P+LOO5QZke7yPNYXQ+ziUBuEHSZozmxZxdJhR13r0ZZ7XGJYrGRO2EiZxucQwCLGeP8rW1AigEqPsdn44GgAvK4ErJLc9RPZxdRCIcR8jRnMXxbIHLlLTawlgJNi8GTYRTq1/A="

cache:
  directories:
    - node_modules
    - vendor

before_install:
  - sudo apt-get update -y
  - sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean -y
  - sudo rm -rf /etc/mysql
  - sudo apt-get install apt-transport-https curl -y
  - sudo mkdir -p /etc/apt/keyrings
  - sudo apt install -y software-properties-common
  - sudo sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
  - sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] https://mariadb.mirror.liquidtelecom.com/repo/11.4/ubuntu focal main'
  - sudo apt update -y
  - sudo apt-get -y install mariadb-server mariadb-client
  - sudo apt-get install php-xdebug

before_script:
  - cp .env.travis .env
  - sudo mariadb -e 'CREATE DATABASE testing;'
  - sudo mariadb -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY '';"
  - sudo mariadb -e "GRANT ALL ON testing.* TO 'travis'@'localhost';"
  - composer self-update
  - composer install --no-interaction
  - composer require --dev php-coveralls/php-coveralls
  - php artisan key:generate
  - sed -i "s/^LITTLEJWT_KEY_PHRASE=.*/LITTLEJWT_KEY_PHRASE=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - sed -i "s/^LITTLEJWT_KEY_PHRASE_REFRESH=.*/LITTLEJWT_KEY_PHRASE_REFRESH=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - php artisan migrate --no-interaction -vvv
  
script:
  - mkdir -p build/logs
  - php artisan test --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls.php -v
