dist: focal
language: php

php:
  - 8.2
  - 8.3

before_install:
  - sudo apt-get update -y
  - sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean -y
  - sudo rm -rf /etc/mysql
  - sudo apt-get install apt-transport-https curl -y
  - sudo mkdir -p /etc/apt/keyrings
  - sudo curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'
  - sudo mkdir -p /etc/apt/sources.list.d
  - |
    sudo tee /etc/apt/sources.list.d/mariadb.sources > /dev/null <<EOF
    # MariaDB 11.4 repository list - created 2025-02-02 20:35 UTC
    # https://mariadb.org/download/
    X-Repolib-Name: MariaDB
    Types: deb
    # deb.mariadb.org is a dynamic mirror if your preferred mirror goes offline. See https://mariadb.org/mirrorbits/ for details.
    # URIs: https://deb.mariadb.org/11.4/ubuntu
    URIs: https://mirrors.xtom.com/mariadb/repo/11.4/ubuntu
    Suites: focal
    Components: main main/debug
    Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp
    EOF
  - sudo apt-get -y upgrade
  - sudo apt-get -y install mariadb-server mariadb-client
  - sudo journalctl -xe

env:
  global:
    - DB_CONNECTION=mysql
    - DB_DATABASE=testing
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - MAIL_MAILER=log

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mariadb -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - sed -i "s/^LITTLEJWT_KEY_PHRASE=.*/LITTLEJWT_KEY_PHRASE=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - sed -i "s/^LITTLEJWT_KEY_PHRASE_REFRESH=.*/LITTLEJWT_KEY_PHRASE_REFRESH=$(php artisan littlejwt:phrase -d | sed -n '/.*/{n;p}')/" .env
  - php artisan migrate --no-interaction -vvv
  
script:
  - php artisan test
