import React from 'react';
import { Badge, Row } from 'reactstrap';
import { Tag } from 'react-tag-autocomplete';

import UnsavedChangesWarning from '@admin/components/UnsavedChangesWarning';
import Heading, { HeadingTitle } from '@admin/layouts/admin/Heading';

import ArticleFormikProvider, { ArticleFormValues } from '@admin/components/blog/articles/containers/formik/ArticleFormikProvider';
import EditArticleActionPanel from '@admin/components/blog/articles/containers/edit/panel/EditArticleActionPanel';
import ArticleEditor from '@admin/components/blog/articles/editor/ArticleEditor';

import Article from '@admin/utils/api/models/Article';
import Revision from '@admin/utils/api/models/Revision';

interface EditArticleContainerProps {
    article: Article;
    revision: Revision;
    tags: Tag[];
}

const EditArticleContainer: React.FC<EditArticleContainerProps> = ({ article, revision, tags }) => {
    const initialValues = React.useMemo<ArticleFormValues>(() => ({
        title: article.article.title,
        autoGenerateSlug: article.isSlugAutoGenerated,
        slug: article.article.slug,
        content: revision.revision.content,
        autoGenerateSummary: revision.revision.summary_auto,
        summary: revision.revision.summary,
        mainImage: article.mainImage ? { src: article.mainImage.url, description: article.mainImage.description } : undefined,
        uploadedImages: [],
        tags: tags
    }), [article, revision]);

    return (
        <>
            <ArticleFormikProvider initialValues={initialValues} inputs={{}}>
                {({ formik, errors, inputs }) => (
                    <>
                        <UnsavedChangesWarning enabled={formik.dirty} />

                        <Row>
                            <Heading>
                                <HeadingTitle>
                                    Edit Post
                                    {formik.dirty && (
                                        <small className='ms-1 text-body-secondary'>
                                            <Badge color='secondary'>Unsaved Changes</Badge>
                                        </small>
                                    )}
                                </HeadingTitle>

                                <div className='d-flex'>
                                    <EditArticleActionPanel formik={formik} article={article} revision={revision} />
                                </div>
                            </Heading>
                        </Row>

                        <ArticleEditor errors={errors} inputs={inputs} />
                    </>
                )}
            </ArticleFormikProvider>
        </>
    );
}

export default EditArticleContainer;
export { EditArticleContainerProps };
