<?php

return [
    "When Chuck Norris throws exceptions, it's across the room.",
    'All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.',
    "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.",
    'Chuck Norris writes code that optimizes itself.',
    "Chuck Norris can't test for equality because he has no equal.",
    "Chuck Norris doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().",
    "Chuck Norris's first program was kill -9.",
    'Chuck Norris burst the dot com bubble.',
    'All browsers support the hex definitions #chuck and #norris for the colors black and blue.',
    "MySpace actually isn't your space, it's Chuck's (he just lets you use it).",
    'Chuck Norris can write infinite recursion functions and have them return.',
    'Chuck Norris can solve the Towers of Hanoi in one move.',
    'The only pattern Chuck Norris knows is the God Object.',
    'Chuck Norris finished World of Warcraft.',
    'Project managers never ask Chuck Norris for estimations... ever.',
    "Chuck Norris doesn't use web standards as the web will conform to him.",
    '"It works on my machine" always holds true for Chuck Norris.',
    'Whiteboards are white because Chuck Norris scared them that way.',
    "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts.",
    'Chuck Norris can delete the Recycling Bin.',
    "Chuck Norris's beard can type 140 words per minute.",
    'Chuck Norris can unit test entire applications with a single assert.',
    "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
    "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris.",
    'When Chuck Norris is web surfing websites get the message "Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?".',
    'Chuck Norris can overflow your stack just by looking at it.',
    'To Chuck Norris, everything contains a vulnerability.',
    "Chuck Norris doesn't need sudo, he just types \"Chuck Norris\" before his commands.",
    "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses.",
    'Chuck Norris can access private methods.',
    'Chuck Norris can instantiate an abstract class.',
    'Chuck Norris does not need to know about class factory pattern. He can instantiate interfaces.',
    'The class object inherits from Chuck Norris',
    'For Chuck Norris, NP-Hard = O(1).',
    "Bill Gates thinks he's Chuck Norris. Chuck Norris actually laughed. Once.",
    "Chuck Norris is actually the front man for Apple. He let's Steve Jobs run the show when he's on a mission. Chuck Norris is always on a mission.",
    "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
    "Chuck Norris solved the Travelling Salesman problem in O(1) time. Here's the pseudo-code: Break salesman into N pieces. Kick each piece to a different city.",
    'No statement can catch the ChuckNorrisException.',
    "Chuck Norris doesn't pair program.",
    'Chuck Norris can write multi-threaded applications with a single thread.',
    "Chuck Norris doesn't need to use AJAX because pages are too afraid to postback anyways.",
    "Chuck Norris doesn't use reflection, reflection asks politely for his help.",
    "There is no Esc key on Chuck Norris' keyboard, because no one escapes Chuck Norris.",
    'Chuck Norris can binary search unsorted data.',
    'Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.',
    "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise.",
    'Chuck Norris went out of an infinite loop.',
    'If Chuck Norris writes code with bugs, the bugs fix themselves.',
    'Chuck Norris hosting is 101% uptime guaranteed.',
    "Chuck Norris's keyboard has the Any key.",
    'Chuck Norris can access the DB from the UI.',
    "Chuck Norris' programs never exit, they terminate.",
    'Chuck Norris insists on strongly-typed programming languages.',
    'Chuck Norris protocol design method has no status, requests or responses, only commands.',
    'Chuck Norris programs occupy 150% of CPU, even when they are not executing.',
    'Chuck Norris can spawn threads that complete before they are started.',
    'Chuck Norris programs do not accept input.',
    'Chuck Norris can install Internet Explorer without installing Windows.',
    "Chuck Norris doesn't need an operating system.",
    "Chuck Norris's OSI network model has only one layer - Physical.",
    'Chuck Norris can compile syntax errors.',
    'Every SQL statement that Chuck Norris codes has an implicit "COMMIT" in its end.',
    'Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All way down. Always.',
    'Chuck Norris does not code in cycles, he codes in strikes.',
    "Chuck Norris doesn't use a computer because a computer does everything slower than Chuck Norris.",
    'Chuck Norris compresses his files by doing a flying round house kick to the hard drive.',
    'Chuck Norris solved the halting problem.',
    "Chuck Norris doesn't cheat death. He wins fair and square.",
    'Chuck Norris once won a game of connect four in 3 moves.',
    "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.",
    'Chuck Norris can do a wheelie on a unicycle.',
    'Chuck Norris can win in a game of Russian roulette with a fully loaded gun.',
    'Chuck Norris eats lightning and poops out thunder.',
    'Chuck Norris can retrieve anything from /dev/null.',
    'No one has ever pair-programmed with Chuck Norris and lived to tell about it.',
    "No one has ever spoken during review of Chuck Norris' code and lived to tell about it.",
    "Chuck Norris doesn't use GUI, he prefers COMMAND line.",
    "Chuck Norris doesn't use Oracle, he is the Oracle.",
    'Chuck Norris can dereference NULL.',
    'Jesus can walk on water, but Chuck Norris can swim through land.',
    "A diff between your code and Chuck Norris's is infinite.",
    'The Chuck Norris Eclipse plugin made alien contact.',
    'Chuck Norris is the ultimate mutex, all threads fear him.',
    "Don't worry about tests, Chuck Norris's test cases cover your code too.",
    "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS.",
    "Chuck Norris's log statements are always at the FATAL level.",
    "Chuck Norris's database has only one table, 'Kick', which he DROPs frequently.",
    "When Chuck Norris break the build, you can't fix it, because there is not a single line of code left.",
    'Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest.',
    "Chuck Norris's programs can pass the Turing Test by staring at the interrogator.",
    "If you try to kill -9 Chuck Norris's programs, it backfires.",
    "Chuck Norris's brain waves are suspected to be harmful to cell phones.",
    'Chuck Norris does infinite loops in 4 seconds.',
    'Product Owners never ask Chuck Norris for more features. They ask for mercy.',
    'Product Owners never argue with Chuck Norris after he demonstrates the DropKick feature.',
    'Chuck Norris killed two stones with one bird.',
    'Chuck Norris can speak Braille.',
    'Chuck Norris can overwrite a locked variable.',
    'Chuck Norris knows the value of NULL, and he can sort by it too.',
    'Chuck Norris can install a 64 bit operating system on 32 bit machines.',
    'Chuck Norris can write to an output stream.',
    'Chuck Norris can read from an input stream.',
    'Chuck Norris never has to build his program to machine code. Machines have learnt to interpret Chuck Norris code.',
    "Chuck Norris' unit tests don't run. They die.",
    'Chuck Norris sits at the stand-up meeting.',
    "Chuck Norris doesn't need an account. He just logs in.",
    "How many Chuck Norris' does it take to screw in a light bulb? None, he will screw it all.",
    'Chuck Norris causes the Windows Blue Screen of Death.',
    'Chuck Norris can download emails with his pick-up.',
    'Chuck Norris can make a class that is both abstract and final.',
    'Code runs faster when Chuck Norris watches it.',
    'Chuck Norris does not need a watch, he decides what time it is.',
    "Chuck Norris already went to Moon and Mars, that's why there are no signs of life.",
    'Once a police officer caught Chuck Norris, the cop was lucky enough to escape with a warning.',
    "Chuck Norris knows Victoria's secret.",
    "Dark spots on the Moon are the result of Chuck Norris' shooting practice.",
    "Chuck Norris died 20 years ago, death just doesn't have the courage to tell him.",
    "There is no April 1st in Chuck Norris' calendar, because no one can fool him.",
    "Onions don't make Chuck Norris cry. Chuck Norris makes onions cry.",
    'Chuck Norris can watch the radio.',
    'Chuck Norris built the hospital he was born in.',
    'Once Chuck Norris signed a cheque and the bank bounced.',
    'Chuck Norris can drown a fish.',
    'Once death had a near Chuck Norris experience.',
    'Once Chuck Norris and Superman had a competition. The loser had to wear his underwear over his pants.',
    'Chuck Norris can make fire using two ice cubes.',
    'Chuck Norris tears can cure the cancer, but the sad thing is Chuck Norris never cries.',
    'Chuck Norris can remember the future.',
    "Chuck Norris doesn't age, because time cannot keep up with him.",
    'Ghosts are actually caused by Chuck Norris killing people faster than Death can process them.',
    'Chuck Norris understands every definition in the Oxford Thesaurus, except one - "mercy".',
    "Chuck Norris doesn't need a keyboard, he tells the computer to write something and it does it.",
    'Chuck Norris once went to the bathroom in a semi truck - that truck is now known as Optimus Prime.',
    'Chuck Norris plays pool with comets and astroids. He shoots them into black holes.',
    "There was never anything wrong with Achilles' heel until he got mad and decided to kick Chuck Norris.",
    'Did you know that Chuck Norris was in every Star Wars movie? He was "The Force".',
    "Knock knock, who's there? Chuck Norris! Chuck Norris who? Sorry, the joke is over when Chuck Norris gets involved!",
    "Chuck Norris doesn't win, he allows you to lose.",
    'Tornados occur when Chuck Norris sneezes.',
    'Chuck Norris once sold eBay to eBay on eBay.',
    'Chuck Norris can build a snowman out of rain.',
    'Chuck Norris made the sun by rubbing his hands together.',
    "Chuck Norris doesn't turn on his faucet, he stares at it until it cries.",
    'Chuck Norris puts sunglasses on to protect the sun from his eyes.',
    'Chuck Norris can lock a safe and keep the key inside it.',
    'Chuck Norris convinced the sun to not rise.',
    'Chuck Norris always plugs in a USB cable on the first try.',
    'Police officers get a ticket when they catch Chuck Norris speeding.',
    'Everytime Chuck Norris farts, his DNA changes.',
    'Chuck Norris can reverse any one-way function.',
    'The Quicksort was originally called the Chuck Norris sort.',
    "Chuck Norris doesn't use sorting algorithms, sorting algorithms use Chuck Norris.",
    'Chuck Norris does not sort, he orders.',
    "Chuck Norris doesn't use strongly-typed languages. He uses strong languages.",
    "Chuck Norris doesn't use versions because his programs are always 100%.",
    "It's impossible to catch the ChuckNorrisException.",
    'Chuck Norris can write multi-threaded applications with a single thread.',
    "Chuck Norris doesn't use a computer because a computer does everything slower than Chuck Norris.",
    'ChatGPT is too scared to tell Chuck Norris jokes.',
];
