#!/usr/bin/env sh

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Run supervisord in the background
exec /usr/bin/supervisord -c /etc/supervisor.d/supervisord.conf &

# This is the original entrypoint for the PHP image:
exec docker-php-entrypoint php-fpm
