<?php

namespace App\Models;

use App\Models\Collections\ArticleCollection;
use App\Traits\Models\Postable;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

class Article extends Model
{
    use HasFactory;
    use Postable;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected $fillable = [
        'title',
        'slug'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'published_at' => 'datetime',
    ];

    /**
     * Create a new Eloquent Collection instance.
     *
     * @param  array  $models
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function newCollection(array $models = [])
    {
        return new ArticleCollection($models);
    }

    /**
     * Gets the current revision
     *
     * @return mixed
     */
    public function currentRevision()
    {
        return $this->belongsTo(Revision::class, 'current_revision');
    }

    /**
     * Gets the revisions of this article
     *
     * @return mixed
     */
    public function revisions()
    {
        return $this->hasMany(Revision::class);
    }

    /**
     * Gets the tags that this article has.
     *
     * @return mixed
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Gets comments for this article.
     *
     * @return mixed
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * Gets images for this article.
     *
     * @return mixed
     */
    public function images()
    {
        return $this->hasMany(ArticleImage::class);
    }

    /**
     * Gets the main image (if any)
     *
     * @return mixed
     */
    public function mainImage()
    {
        return $this->belongsTo(ArticleImage::class, 'main_image');
    }

    /**
     * Scope a query to only include published articles.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublished($query)
    {
        return $query->whereNotNull('published_at')->where('published_at', '<=', now());
    }

    /**
     * Scope a query to sort by published_at column value.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSortedByPublishDate($query)
    {
        return $query->latest('published_at');
    }

    /**
     * Gets the active revision for this article.
     *
     * @return Revision
     */
    public function revision()
    {
        if (! is_null($this->currentRevision)) {
            return $this->currentRevision;
        }

        return $this->revisions()->latest()->first();
    }

    /**
     * Get and set the summary
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function summary(): Attribute
    {
        return Attribute::make(
            get: fn ($value, $attributes) => is_null($value) ? static::generateSummaryFrom($this->revision()->content) : $value,
            set: fn ($value) => is_string($value) ? Str::stripTags($value) : $value,
        );
    }

    /**
     * Checks if summary is auto generated
     *
     * @return bool
     */
    public function isSummaryAutoGenerated()
    {
        return is_null($this->summary);
    }

    /**
     * Checks if summary is auto generated
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    public function summaryAuto(): Attribute
    {
        return Attribute::get(fn () => $this->isSummaryAutoGenerated());
    }

    /**
     * Creates public link to this article
     *
     * @param bool $absolute
     * @return string
     */
    public function createPublicLink(bool $absolute = true)
    {
        return URL::route('blog.single', ['article' => $this], $absolute);
    }

    /**
     * Creates temporary signed URL to this article
     *
     * @param int $minutes Minutes until URL expires (default: 30)
     * @param bool $absolute If true, absolute URL is returned. (default: true)
     * @return string
     */
    public function createPrivateUrl(int $minutes = 30, bool $absolute = true)
    {
        return URL::temporarySignedRoute('blog.single', $minutes * 60, ['article' => $this], $absolute);
    }

    /**
     * Generates summary from description
     *
     * @param string $description
     * @return string
     */
    public static function generateSummaryFrom(string $description)
    {
        $sentences = Str::sentences(Str::stripTags($description), 3);

        return Arr::join($sentences, ' ');
    }
}
