<?php

namespace App\Components\Fakers\Providers;

use Faker\Provider\Base;

class Technology extends Base
{
    protected static $technologies = [
        'Python',
        'JavaScript',
        'Java',
        'C#',
        'C++',
        'Ruby',
        'PHP',
        'Swift',
        'Kotlin',
        'TypeScript',
        'Go',
        'Rust',
        'HTML',
        'CSS',
        'SQL',
        'React',
        'React Native',
        'Next.js',
        'Angular',
        'Vue.js',
        'Node.js',
        'Django',
        'Spring',
        'Laravel',
        'Symfony',
        'Express.js',
        'Flask',
        'Ruby on Rails',
        'ASP.NET',
        'Flutter',
        'Unity',
        'TensorFlow',
        'PyTorch',
        'Docker',
        'Kubernetes',
        'Git',
        'Jenkins',
        'AWS',
        'Azure',
        'Google Cloud Platform',
        'Firebase',
        'MongoDB',
        'MySQL',
        'MariaDB',
        'PostgreSQL',
        'SQLite',
        'Redis',
        'Elasticsearch',
        'GraphQL',
        'RESTful API',
        'SOAP',
        'gRPC',
        'OAuth',
        'JWT',
        'CI/CD',
        'DevOps',
        'Agile',
        'Scrum',
        'Kanban',
        'GitLab',
        'Bitbucket',
        'Jira',
        'Trello',
        'Visual Studio Code',
        'Sublime Text',
        'Atom',
        'Vim',
        'IntelliJ IDEA',
        'Eclipse',
        'PyCharm',
        'WebStorm',
        'Android Studio',
        'Xcode',
        'Unity',
        'Blender',
        'Photoshop',
        'Illustrator',
        'Sketch',
        'Figma',
        'InVision',
        'Zeplin',
        'Adobe XD',
        'Adobe Creative Cloud',
        'Microsoft Office',
        'Google Workspace',
        'Slack',
        'Microsoft Teams',
        'Zoom',
        'Discord',
        'GitHub',
        'GitLab',
        'Bitbucket',
        'Stack Overflow',
        'Dev.to',
        'Medium',
        'Hacker News',
        'Reddit',
        'Twitter',
        'LinkedIn',
        'Facebook',
        'Instagram',
        'TikTok',
        'Snapchat',
        'WhatsApp',
        'Messenger',
        'Signal',
        'Telegram',
        'Skype',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Cisco Webex',
        'Jitsi Meet',
        'Discord',
        'Slack',
        'Asana',
        'Trello',
        'Basecamp',
        'Monday.com',
        'Notion',
        'Todoist',
        'Microsoft To Do',
        'Google Tasks',
        'Evernote',
        'OneNote',
        'Bear',
        'Dropbox',
        'Google Drive',
        'Microsoft OneDrive',
        'Box',
        'Nextcloud',
        'pCloud',
        'SpiderOak',
        'Sync.com',
        'Mega',
        'IDrive',
        'Backblaze',
        'Carbonite',
        'CrashPlan',
        'Acronis True Image',
        'Norton',
        'McAfee',
        'Bitdefender',
        'Avast',
        'AVG',
        'Kaspersky',
        'Trend Micro',
        'Sophos',
        'Symantec',
        'Malwarebytes',
        'ESET',
        'Palo Alto Networks',
        'Cisco',
        'Fortinet',
        'Check Point',
        'Juniper Networks',
        'SonicWall',
        'Barracuda Networks',
        'FireEye',
        'Proofpoint',
        'Splunk',
        'LogRhythm',
        'QRadar',
        'ArcSight',
        'Sumo Logic',
        'Graylog',
        'Elastic Stack',
        'SolarWinds',
        'Nagios',
        'Zabbix',
        'PRTG',
        'Datadog',
        'New Relic',
        'AppDynamics',
        'Dynatrace',
        'Splunk',
        'Loggly',
        'Papertrail',
        'Syslog-ng',
        'Rsyslog',
        'Fluentd',
        'Logstash',
        'Filebeat',
        'Winlogbeat',
        'Metricbeat',
        'Heartbeat',
        'Packetbeat',
        'Auditbeat',
        'Journalbeat',
        'Functionbeat',
        'Traefik',
        'Envoy',
        'HAProxy',
        'nginx',
        'Apache',
        'Caddy',
        'IIS',
        'Docker Swarm',
        'Kubernetes',
        'Amazon ECS',
        'Google Kubernetes Engine',
        'Azure Kubernetes Service',
        'Red Hat OpenShift',
        'VMware Tanzu',
        'HashiCorp Nomad',
        'Rancher',
        'Portainer',
        'Kubeadm',
        'Minikube',
        'k3s',
        'microk8s',
        'Docker Desktop',
        'Podman',
        'Buildah',
        'Kustomize',
        'Helm',
        'Kompose',
        'Skaffold',
        'Kubeapps',
        'Grafana',
        'Prometheus',
        'Jaeger',
        'Zipkin',
        'ELK Stack',
        'TICK Stack',
        'InfluxDB',
        'Telegraf',
        'Chronograf',
        'Kapacitor',
        'Ceph',
        'GlusterFS',
        'OpenStack',
        'CloudStack',
        'Proxmox VE',
        'oVirt',
        'VMware vSphere',
        'Hyper-V',
        'Xen',
        'KVM',
        'QEMU',
        'VirtualBox',
        'Parallels Desktop',
        'Vagrant',
        'Terraform',
        'AWS CloudFormation',
        'Azure Resource Manager',
        'Google Cloud Deployment Manager',
        'Puppet',
        'Chef',
        'Ansible',
        'SaltStack',
        'Juju',
        'Rundeck',
        'StackStorm',
        'Foreman',
        'OpenNebula',
        'OpenShift Ansible',
        'kops',
        'AWS CDK',
        'Serverless Framework',
        'Troposphere',
        'Pulumi',
        'Cloudify',
        'Morpheus',
        'CloudBolt',
        'Scalr',
        'RightScale',
        'Red Hat Satellite',
        'Spacewalk',
        'Foreman',
        'Katello',
        'ManageIQ',
        'OpenStack',
        'vRealize Automation',
        'Habitat',
        'Concourse',
        'Spinnaker',
        'Drone',
        'Jenkins X',
        'Tekton',
        'CircleCI',
        'Travis CI',
        'GitHub Actions',
        'GitLab CI/CD',
        'Bitbucket Pipelines',
        'Azure Pipelines',
        'AWS CodePipeline',
        'Windows',
        'Linux',
        'MacOS',
        'iOS',
        'Android',
    ];

    /**
     * Gets a random technology.
     *
     * @return string
     */
    public function technology(): string
    {
        return static::randomElement(static::$technologies);
    }
}
